# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Ketogenic Diet
titletwo: The Ketogenic Diet | Where more fat is actually less
email: williamsheean17@sasaustin.org
description: > # this means to ignore newlines until "baseurl:"
  Expolore this website to learn about my experience as an 18 year old athletic male on the ketogenic diet.
  You can see why it works and how to do it on your own.
  Keep looking and you'll find eating tips, comparisons, charts, pictures and more!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  wksheehan
theme: jekyll-theme-midnight

# Build settings
markdown: kramdown
