# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Ketogenic Diet
email: williamsheean17@sasaustin.org
description: > # this means to ignore newlines until "baseurl:"
  This blog containts daily posts about my experience on the ketogenic diet,
  along with the research I've done on the science behind the diet. Explore
  the website to discover meal plans, comparisons, and charts!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  wksheehan

# Build settings
markdown: kramdown
